# Site Settings
title: Ernesto | Web personal
email: ernestoaguaysol@gmail.com
description: Post para el blog personal.
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ernestoaguaysol.github.io" # the base hostname & protocol for your site
google_analytics: "UA-108263017-1"

# User Settings
username: ernestoaguaysol
user_description: Developer full stack.
disqus_username: ernestoaguaysol

# Social Media
# Remove the item if you don't need it
github_username: ernestoaguaysol
facebook_username: ernestoaguaysol
twitter_username: ernestoaguaysol
instagram_username: ernestoaguaysol
linkedin_username: ernestoaguaysol/
# medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Inicio
    url: /
  - title: Acerca de mi
    url: /about/
  - title: Contacto
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
